In [21]:
from bs4 import BeautifulSoup
import requests
import openpyxl

In [24]:
excel = openpyxl.Workbook()
sheet = excel.active
sheet.title = "Top 100 movies"
sheet.append(["Name","Year","Rating","Rank"])
try:
    source = requests.get("https://editorial.rottentomatoes.com/guide/100-best-classic-movies/")
    source.raise_for_status()
    
    soup = BeautifulSoup(source.text, 'html.parser')
    movies = soup.find("div", class_ = "articleContentBody").find_all("div", class_ = "row countdown-item")
    for movie in movies:
        name = movie.find("div", class_ = "article_movie_title").a.text
        year = movie.find("span", class_="subtle start-year").text.strip("()")
        rating = movie.find("span", class_="tMeterScore").text.strip("()")
        rank = movie.find("div", class_ = "countdown-index").text.strip("#")
        
        sheet.append([name,year,rating,rank])  
    
except Exception as e:
    print(e)

excel.save("Top 100 movies.xlsx")

In [25]:
import numpy as np
for j in range(5):
    print(np.random.permutation(list(range(10))))

[6 9 7 1 0 5 4 2 3 8]
[1 2 6 3 4 9 5 0 7 8]
[8 3 1 5 4 2 7 9 6 0]
[9 0 1 7 3 4 6 2 5 8]
[8 1 9 4 5 3 6 0 2 7]


In [26]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams["figure.figsize"]=(20,10)

In [27]:
def generate_data(df, sequence_length = 15, step = 1):
  X=df.iloc[:,:-1]
  y=df.y
  X_local = []
  y_local = []
  for start in range(0, len(X) - sequence_length, step):
    end = start + sequence_length
    X_local.append(X[start:end])
    y_local.append(y[end-1])
  return np.array(X_local), np.array(y_local)

In [28]:
df = pd.read_csv("agniva_crossing_140_125.csv")
df.head()

x1        x2        x3        x4        x5        x6        x7  \
0  0.653169  0.405584  0.654795  0.399523  0.655494  0.399327  0.656238   
1  0.653210  0.405591  0.654805  0.399516  0.655499  0.399318  0.656241   
2  0.653800  0.406057  0.655155  0.399920  0.655794  0.399704  0.656492   
3  0.653948  0.406487  0.655214  0.400391  0.655829  0.400135  0.656506   
4  0.653749  0.406785  0.654989  0.400744  0.655549  0.400432  0.656154   

         x8        x9       x10  ...       x58       x59       x60       x61  \
0  0.399052  0.654095  0.399645  ...  0.650608  0.682885  0.668998  0.677082   
1  0.399039  0.654133  0.399636  ...  0.650805  0.682884  0.669085  0.677318   
2  0.399402  0.654620  0.400051  ...  0.651157  0.682677  0.669166  0.678227   
3  0.399804  0.654752  0.400574  ...  0.651392  0.682640  0.670060  0.678116   
4  0.400064  0.654644  0.400973  ...  0.651388  0.681025  0.670081  0.678069   

        x62       x63       x64       x65       x66    y  
0  0.663183  0.664685  0.676659  0.656088  0.660782  0.0  
1  0.663795  0.664679  0.675925  0.656422  0.660773  0.0  
2  0.664675  0.663131  0.671729  0.657012  0.660824  0.0  
3  0.664869  0.663037  0.672159  0.657177  0.661460  0.0  
4  0.664858  0.660501  0.671248  0.657157  0.661525  0.0  

[5 rows x 67 columns]

In [47]:
df[df["y"]==0]

x1        x2        x3        x4        x5        x6        x7  \
0    0.653169  0.405584  0.654795  0.399523  0.655494  0.399327  0.656238   
1    0.653210  0.405591  0.654805  0.399516  0.655499  0.399318  0.656241   
2    0.653800  0.406057  0.655155  0.399920  0.655794  0.399704  0.656492   
3    0.653948  0.406487  0.655214  0.400391  0.655829  0.400135  0.656506   
4    0.653749  0.406785  0.654989  0.400744  0.655549  0.400432  0.656154   
..        ...       ...       ...       ...       ...       ...       ...   
135  0.643206  0.407983  0.644051  0.401077  0.644652  0.400570  0.645252   
136  0.643415  0.407888  0.644247  0.401059  0.644844  0.400561  0.645435   
137  0.643535  0.407801  0.644394  0.401008  0.645010  0.400499  0.645616   
138  0.643514  0.407655  0.644301  0.400966  0.644868  0.400456  0.645420   
139  0.643330  0.407618  0.644091  0.400912  0.644619  0.400401  0.645129   

           x8        x9       x10  ...       x58       x59       x60  \
0    0.399052  0.654095  0.399645  ...  0.650608  0.682885  0.668998   
1    0.399039  0.654133  0.399636  ...  0.650805  0.682884  0.669085   
2    0.399402  0.654620  0.400051  ...  0.651157  0.682677  0.669166   
3    0.399804  0.654752  0.400574  ...  0.651392  0.682640  0.670060   
4    0.400064  0.654644  0.400973  ...  0.651388  0.681025  0.670081   
..        ...       ...       ...  ...       ...       ...       ...   
135  0.399974  0.643388  0.401167  ...  0.638261  0.676884  0.662484   
136  0.399997  0.643489  0.401198  ...  0.638148  0.677551  0.662534   
137  0.399933  0.643500  0.401200  ...  0.637434  0.677871  0.662744   
138  0.399899  0.643600  0.401113  ...  0.637610  0.675837  0.662346   
139  0.399845  0.643605  0.401096  ...  0.637817  0.672064  0.661656   

          x61       x62       x63       x64       x65       x66    y  
0    0.677082  0.663183  0.664685  0.676659  0.656088  0.660782  0.0  
1    0.677318  0.663795  0.664679  0.675925  0.656422  0.660773  0.0  
2    0.678227  0.664675  0.663131  0.671729  0.657012  0.660824  0.0  
3    0.678116  0.664869  0.663037  0.672159  0.657177  0.661460  0.0  
4    0.678069  0.664858  0.660501  0.671248  0.657157  0.661525  0.0  
..        ...       ...       ...       ...       ...       ...  ...  
135  0.673943  0.647024  0.659654  0.663188  0.656656  0.655198  0.0  
136  0.671808  0.647953  0.659649  0.662981  0.652090  0.653301  0.0  
137  0.667910  0.648540  0.659480  0.664377  0.646910  0.653162  0.0  
138  0.663571  0.648804  0.659716  0.664480  0.641809  0.652221  0.0  
139  0.664422  0.659019  0.662733  0.664499  0.637907  0.651174  0.0  

[140 rows x 67 columns]

In [39]:
df[df["y"]==1]

x1        x2        x3        x4        x5        x6        x7  \
140  0.643345  0.407821  0.644053  0.401302  0.644560  0.400784  0.645052   
141  0.643457  0.407887  0.644075  0.401603  0.644628  0.401113  0.645135   
142  0.643315  0.408279  0.643909  0.402114  0.644403  0.401658  0.644863   
143  0.643305  0.409063  0.643884  0.402870  0.644341  0.402442  0.644763   
144  0.642775  0.410313  0.643339  0.403985  0.643730  0.403548  0.644113   
..        ...       ...       ...       ...       ...       ...       ...   
291  0.295436  0.404888  0.297488  0.398240  0.298888  0.397895  0.300418   
292  0.295175  0.404892  0.297273  0.398141  0.298666  0.397760  0.300178   
293  0.296604  0.401382  0.298539  0.395028  0.299955  0.394599  0.301503   
294  0.296401  0.399982  0.298400  0.393381  0.299835  0.392832  0.301376   
295  0.293083  0.400569  0.295217  0.393825  0.296494  0.393283  0.297764   

           x8        x9       x10  ...       x58       x59       x60  \
140  0.400237  0.643648  0.401473  ...  0.637607  0.672318  0.662153   
141  0.400607  0.643840  0.401730  ...  0.637529  0.671698  0.658814   
142  0.401191  0.643777  0.402221  ...  0.636832  0.678139  0.662474   
143  0.401985  0.643791  0.402920  ...  0.636464  0.680655  0.664424   
144  0.403074  0.643370  0.404053  ...  0.635664  0.678568  0.656995   
..        ...       ...       ...  ...       ...       ...       ...   
291  0.397606  0.294246  0.399081  ...  0.668773  0.319324  0.681494   
292  0.397459  0.294043  0.399172  ...  0.668676  0.318977  0.681351   
293  0.394321  0.295311  0.396185  ...  0.665047  0.320273  0.678224   
294  0.392459  0.295224  0.394914  ...  0.664178  0.320202  0.676997   
295  0.392872  0.292181  0.395398  ...  0.664216  0.319766  0.677536   

          x61       x62       x63       x64       x65       x66    y  
140  0.659650  0.661330  0.664294  0.664748  0.633395  0.649978  1.0  
141  0.659476  0.664313  0.663756  0.665492  0.628452  0.648684  1.0  
142  0.646907  0.660618  0.663844  0.666317  0.622142  0.646534  1.0  
143  0.637487  0.653346  0.664203  0.667093  0.617971  0.644333  1.0  
144  0.632386  0.650648  0.663992  0.667612  0.612636  0.641316  1.0  
..        ...       ...       ...       ...       ...       ...  ...  
291  0.314809  0.681566  0.298176  0.688667  0.291439  0.686978  1.0  
292  0.316795  0.681602  0.298142  0.688671  0.293348  0.686842  1.0  
293  0.318384  0.677077  0.301519  0.685487  0.296156  0.681627  1.0  
294  0.317549  0.675966  0.300793  0.684496  0.295615  0.680469  1.0  
295  0.317191  0.676038  0.300406  0.684826  0.295701  0.680900  1.0  

[156 rows x 67 columns]

In [55]:
df.iloc[280]

x1     0.288198
x2     0.406796
x3     0.290343
x4     0.399343
x5     0.291721
         ...   
x63    0.290591
x64    0.689876
x65    0.289168
x66    0.679486
y      1.000000
Name: 280, Length: 67, dtype: float64

In [29]:
df.shape

(296, 67)

In [32]:
data=[]

x,y=generate_data(df)
data.append([x,y])

In [33]:
data

[[array([[[0.65316927, 0.40558445, 0.65479523, ..., 0.67665899,
           0.65608817, 0.66078156],
          [0.65320992, 0.40559116, 0.65480459, ..., 0.67592543,
           0.65642208, 0.66077346],
          [0.65380019, 0.40605703, 0.65515518, ..., 0.67172927,
           0.65701234, 0.66082364],
          ...,
          [0.65836769, 0.40705031, 0.65929729, ..., 0.67071408,
           0.65825135, 0.66040707],
          [0.6581195 , 0.4073115 , 0.65908378, ..., 0.66983122,
           0.65805858, 0.66004676],
          [0.65797734, 0.40750659, 0.6589911 , ..., 0.66987681,
           0.65693629, 0.65967405]],
  
         [[0.65320992, 0.40559116, 0.65480459, ..., 0.67592543,
           0.65642208, 0.66077346],
          [0.65380019, 0.40605703, 0.65515518, ..., 0.67172927,
           0.65701234, 0.66082364],
          [0.65394849, 0.4064866 , 0.65521431, ..., 0.67215884,
           0.65717685, 0.66146022],
          ...,
          [0.6581195 , 0.4073115 , 0.65908378, ..., 0.66983122,
  

In [48]:
data[0][0][0]

array([[0.65316927, 0.40558445, 0.65479523, 0.3995235 , 0.65549415,
        0.39932737, 0.6562382 , 0.39905232, 0.65409499, 0.39964536,
        0.65427834, 0.39957404, 0.65450412, 0.39937684, 0.66211319,
        0.40027377, 0.66026413, 0.40030813, 0.65583259, 0.41124564,
        0.6547516 , 0.41180667, 0.67716086, 0.42797184, 0.66615504,
        0.43593234, 0.67912519, 0.47998923, 0.668549  , 0.48105982,
        0.66605598, 0.52482659, 0.66241753, 0.52058452, 0.66306096,
        0.5381822 , 0.65902215, 0.53424144, 0.66022688, 0.53625149,
        0.65866035, 0.53451443, 0.66070503, 0.53296435, 0.65938282,
        0.53015351, 0.67323714, 0.52286756, 0.66594326, 0.52348334,
        0.67703384, 0.58782488, 0.66902047, 0.58640879, 0.68026924,
        0.65615368, 0.67331809, 0.65060771, 0.68288529, 0.66899788,
        0.67708164, 0.6631828 , 0.66468483, 0.67665899, 0.65608817,
        0.66078156],
       [0.65320992, 0.40559116, 0.65480459, 0.3995156 , 0.65549922,
        0.39931759, 0.65624

In [49]:
len(data[0][0][0])

15

In [50]:
data[0][1][0]

0.0

In [36]:
len(data[0][0])

281

In [37]:
len(data[0][1])

281

In [38]:
data[0][1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [45]:
data[0][1][125]

0.0

In [46]:
data[0][1][126]

1.0

In [51]:
data[0][0][125]

array([[0.64851016, 0.40300047, 0.64985901, 0.39626616, 0.6511476 ,
        0.39549977, 0.65244865, 0.39466286, 0.64681917, 0.39835379,
        0.64608675, 0.39910144, 0.64537901, 0.39990416, 0.65701288,
        0.39581993, 0.64752966, 0.40279421, 0.65297115, 0.40758285,
        0.64931023, 0.4100194 , 0.67032558, 0.42146775, 0.65914696,
        0.43670321, 0.67986399, 0.46708548, 0.66860843, 0.48046151,
        0.6770435 , 0.5141151 , 0.66746837, 0.51802009, 0.67748421,
        0.52997071, 0.66662633, 0.53257048, 0.67277181, 0.53047448,
        0.66638732, 0.53309143, 0.67197382, 0.52699655, 0.66673589,
        0.52890754, 0.67691123, 0.51753688, 0.67226529, 0.52031553,
        0.67164147, 0.58709204, 0.67488587, 0.58308631, 0.67541319,
        0.65697992, 0.6839267 , 0.64637142, 0.67915446, 0.66901475,
        0.68845177, 0.6581012 , 0.65784061, 0.66956878, 0.66942602,
        0.66157395],
       [0.64667344, 0.40360707, 0.648054  , 0.39690471, 0.6493355 ,
        0.39617452, 0.65063

In [52]:
data[0][0][280]

array([[0.28819761, 0.40679568, 0.29034317, 0.39934289, 0.29172099,
        0.39874178, 0.29312018, 0.3981933 , 0.28735945, 0.40087023,
        0.28652909, 0.40132701, 0.28575322, 0.4017939 , 0.29833063,
        0.40055814, 0.28859508, 0.40402818, 0.2917403 , 0.41221967,
        0.28844425, 0.41440386, 0.30934346, 0.43459886, 0.29485026,
        0.44286171, 0.30931109, 0.48842874, 0.29699621, 0.4912613 ,
        0.29669935, 0.53620118, 0.29196846, 0.52905339, 0.29443988,
        0.54911041, 0.28967726, 0.54176033, 0.29227987, 0.54780078,
        0.28877792, 0.54286909, 0.29260787, 0.54522961, 0.29001528,
        0.53991824, 0.30250105, 0.53589463, 0.2953656 , 0.53543681,
        0.30033165, 0.60402215, 0.29311818, 0.59927726, 0.30718914,
        0.67112428, 0.30407941, 0.66142201, 0.31176871, 0.68226713,
        0.30864552, 0.67213941, 0.29059118, 0.68987572, 0.28916788,
        0.67948568],
       [0.28892291, 0.40693986, 0.29107988, 0.39949971, 0.29249743,
        0.39894938, 0.29394

In [54]:
data[0][0][281]

IndexError: index 281 is out of bounds for axis 0 with size 281

In [53]:
data[0][1][280]

1.0

In [ ]:
0-14 - 0
1-15 -0
2-16-0
3-17-0
-----
125-139 -0
126-140-1
----
280-295 - 1